title: The Sports Gamer Hub
email: your-email@example.com
description: >-
  Your go-to spot for everything sports gaming — FC 26, Call of Duty, 
  Spider-Man 2, NBA 2K26, Madden NFL 26, and more!
baseurl: ""
url: "https://jrwaka.github.io"

theme: minima